# Generated by Django 4.1 on 2022-11-08 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('time_slot', models.CharField(default='', max_length=70)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_Name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('addmission_date', models.DateField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.CharField(max_length=100)),
                ('advance', models.CharField(max_length=100)),
                ('pending', models.CharField(max_length=100)),
            ],
        ),
    ]
