# Generated by Django 4.1 on 2022-11-09 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_appointment_doctor_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('addmission_date', models.DateField(default=django.utils.timezone.now)),
                ('discharge', models.DateField(default=django.utils.timezone.now)),
                ('room_no', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
            ],
        ),
    ]
