# Generated by Django 4.1 on 2022-11-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='addmission_date',
            new_name='admission_date',
        ),
    ]
